[project]
name = "emp-pjs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "keeshore", email = "keeshoreadhis24bcc126@skasc.ac.in" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
emp-pjs = "emp_pjs:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
